### ISSUE TITLE
Cannot resolve the reference

### ISSUE THREAD

**Issue by erdugen** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#10]
Hi Adam,
I am using NewtonSoft.Json 12.0.1, RestSharp 106.5.4 and RestSharp.Newtonsoft.Json 1.5.0 in my application. IOS is working properly in simulator. I get an error when I want to try the iPhone. First, I tried the NewtonSoft version 11.0.2 and got the same error. The problem is fixed when I make the version 12.0.1 and lower the RestSharp version to 106.0.1. Because the error message 106.0.1 has given warning. I hope I can tell in a clear way.

Error message

> Error MT2101: Cannot resolve the reference 'System.Void RestSharp.RestRequest ::. Ctor (System.String)', referenced from the method 'System.Void RestSharp.Serializers.Newtonsoft.Json.RestRequest ::. Ctor (System .String) '' RestSharp, Version = 106.0.1.0, Culture = neutral, PublicKeyToken = 598062e77f915f75 '. (MT2101) (crmmobile.iOS)

**Comment by adamfisher** [comment]
It looks like this has been an issue others have experienced as well directly with RestSharp. However I am able to upgrade to the latest versions as you mentioned above and I'm able to build the project and run all unit tests.

https://github.com/restsharp/RestSharp/issues/1198

Some solutions they mention to try:

- Uninstalling the package and reinstalling
- If the RestSharp dependency is directly installed in your solution, remove it and only rely on the NuGet package dependency.

**Comment by adamfisher** [comment]
`RestSharp.Serializers.Newtonsoft.Json.RestRequest` is just a convenience wrapper that extends `RestSharp.RestRequest` and automatically applies the Newtonsoft serializer. It is optional to use since you can set it in an alternate way as mentioned in the docs.

Regardless, I published release 1.5.1 and recompiled against the latest RestSharp version to ensure they are both consistent.

https://github.com/adamfisher/RestSharp.Serializers.Newtonsoft.Json/releases/tag/1.5.1

**Comment by erdugen** [comment]
The problem is resolved with the latest version. Thanks...
